import {weekOne, weekTwo, weekThree, weekFour, weekFive, weekSix, weekSeven, weekEight, weekNine, weekTen, weekEleven, weekTwelve, weekThirteen, weekFourteen, weekFifteen, weekSixteen, weekSeventeen, weekEighteen, weekNineteen, weekTwenty, weekTwentyOne, weekTwentyTwo, weekTwentyThree, weekTwentyFour, weekTwentyFive, weekTwentySix, weekTwentySeven, weekTwentyEight, weekTwentyNine, weekThirty, weekThirtyOne, weekThirtyTwo, weekThirtyThree, weekThirtyFour, weekThirtyFive, weekThirtySix, weekThirtySeven, weekThirtyEight, weekThirtyNine, weekForty, weekFortyOne, weekFortyTwo, weekFortyThree, weekFortyFour, weekFortyFive, weekFortySix, weekFortySeven, weekFortyEight, weekFortyNine, weekFifty, weekFiftyOne, weekFiftyTwo} from "./bookDataList/week1"
const BOOKPAGE = [
  weekOne,
  weekTwo,
  weekThree,
  weekFour,
  weekFive,
  weekSix,
  weekSeven,
  weekEight,
  weekNine,
  weekTen,
  weekEleven,
  weekTwelve,
  weekThirteen,
  weekFourteen,
  weekFifteen,
  weekSixteen,
  weekSeventeen,
  weekEighteen,
  weekNineteen,
  weekTwenty, 
  weekTwentyOne,
  weekTwentyTwo,
  weekTwentyThree,
  weekTwentyFour,
  weekTwentyFive,
  weekTwentySix,
  weekTwentySeven,
  weekTwentyEight,
  weekTwentyNine,
  weekThirty,
  weekThirtyOne,
  weekThirtyTwo,
  weekThirtyThree,
  weekThirtyFour,
  weekThirtyFive,
  weekThirtySix,
  weekThirtySeven,
  weekThirtyEight,
  weekThirtyNine,
  weekForty,
  weekFortyOne,
  weekFortyTwo,
  weekFortyThree,
  weekFortyFour,
  weekFortyFive,
  weekFortySix,
  weekFortySeven,
  weekFortyEight,
  weekFortyNine,
  weekFifty,
  weekFiftyOne,
  weekFiftyTwo,
  
]

export default BOOKPAGE;